sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "zhangzijian6666"

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDygctiF6PnrKXy2vvq
    access-key-secret: LigQvIa5baBGMxNwPNICsW8N40OhYA
    bucket-name: zijian-java-sky-out
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10